name: Update Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00
  workflow_dispatch: # Allows manual trigger

jobs:
  update-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout chat-scripts repo
      uses: actions/checkout@v2
      with:
        path: chat-scripts

    - name: Checkout chat-play repo
      uses: actions/checkout@v2
      with:
        repository: mefengl/chat-play
        path: chat-play

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies and build
      run: |
        cd chat-play
        npm install -g pnpm
        pnpm install
        pnpm build

    - name: Replace script.user.js
      run: |
        for app_path in chat-play/apps/*; do
          app_name=$(basename "$app_path")
          if [ -d "$app_path" ]; then
            mkdir -p "chat-scripts/$app_name"
            mv "$app_path/dist/script.user.js" "chat-scripts/$app_name/script.user.js"
            if [ -e "$app_path/README.md" ]; then
              cp "$app_path/README.md" "chat-scripts/$app_name/README.md"
            fi
            if [ -e "$app_path/LICENSE" ]; then
              cp "$app_path/LICENSE" "chat-scripts/$app_name/LICENSE"
            fi
            if [ -d "$app_path/LICENSES" ]; then
              cp -r "$app_path/LICENSES" "chat-scripts/$app_name/LICENSES"
            fi
          fi
        done

    - name: Commit and push changes
      run: |
        cd chat-scripts
        git config user.name "冯不游"
        git config user.email "71683364+mefengl@users.noreply.github.com"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update apps" && git push)
